language: ruby

script: ./.travis/concat_file.sh

branches:
  only: master

after_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.travis/decrypt_key.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./.travis/push_to_website.sh; fi'