before_script:
  - wget http://stedolan.github.io/jq/download/linux64/jq && chmod u+x jq
  - npm install -g mocha
  - npm install mocha-phantomjs

script:
  - ./jq '.' locations/*.json
  - ./node_modules/mocha-phantomjs/bin/mocha-phantomjs ./test/index.html